name: Transcribe audio from Drive

on:
  workflow_dispatch:          # també el pots llançar manualment

permissions:
  contents: write

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Instal·lar ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          pip install openai-whisper google-api-python-client google-auth-httplib2 google-auth-oauthlib google-auth

      - name: Run transcription script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: python transcribe2.py

      - name: Commit and push debug files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add debug_transcript.txt 
          git add *.srt
          git commit -m "Afegint fitxers de transcripció" || echo "No hi ha canvis per fer commit"
          git push
