name: Transcribe audio from Drive

on:
  workflow_dispatch:          # també el pots llançar manualment

permissions:
  contents: write

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Instal·lar ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          pip install openai-whisper google-api-python-client google-auth-httplib2 google-auth-oauthlib google-auth 
        
      - name: Run transcription script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python transcribe2.py

      - name: Commit i push dels fitxers transcrits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add transcript/
          git commit -m "Afegir transcripció SRT generada automàticament" || exit 0
          git push

      - name: Enviar notificació Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🎙️ Transcripció d'àudio completada!
            
            📁 Fitxer SRT generat i guardat a: transcript/
            🔗 Veure fitxers: https://github.com/${{ github.repository }}/tree/main/transcript
            
            ✅ Arxiu original esborrat de Google Drive
            ⏰ Completat: ${{ github.event.head_commit.timestamp }}
