name: youtube-update

on:
  workflow_dispatch:

jobs:
  update_video:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade google-auth google-auth-oauthlib google-api-python-client

      - name: Run YouTube update script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          NEW_TITLE: ${{ secrets.NEW_TITLE }}
          NEW_DESCRIPTION: ${{ secrets.NEW_DESCRIPTION }}
        run: python ./youtube_update.py
